version: '3'

services:
  # blog-server:
  #   build: ./server
  #   ports:
  #     - 5000:5000
  #   environment:
  #     - REACT_APP_BASE_URL_BLOG_SERVER=http://localhost:5000/

  react-app:
    build: ./client
    ports:
      - 8000:80
    environment:
      REACT_APP_BASE_URL_BLOG_SERVER: http://localhost:5000/

      







  