version: '3'

 
services:
  blog-server:
    build: ./server
    ports:
      - 5000:5000

  react-app:
    build: ./client
    ports:
      - 3000:3000
    environment:
      - REACT_APP_BASE_URL_BLOG_SERVER=http://localhost:5000/

      







  